Added support fo H2 for local development
a5lab/tabr pull request #14
Opened 2022-11-25 18:34 UTC by yurichervoniy

2022-11-25 18:34 UTC, yurichervoniy commented
You can run application usinng command - ./mvnw clean spring-boot:run -Plocal

2022-11-26 15:55 UTC, arufanov requested changes

2022-11-26 15:55 UTC, arufanov commented on src/main/resources/application-local.yml
> +spring:
@yurichervoniy 
* how can I switch between applciaton.yml & application-local.yml?

2022-11-26 20:26 UTC, arufanov commented on src/main/resources/application-local.yml
> +spring:
@yurichervoniy 
* thanks, I understood.

2022-11-26 20:27 UTC, arufanov approved these changes
@yurichervoniy 
* thanks!

2022-11-26 20:31 UTC, merged

2022-11-26 20:32 UTC, arufanov commented
@yurichervoniy 
* I accepted this pr to test