Changed to boot 3 stable
a5lab/tabr pull request #19
Opened 2022-11-30 21:45 UTC by yurichervoniy

2022-12-01 09:55 UTC, arufanov requested changes
Need discuss some issue, primary on is database schema

2022-12-01 09:55 UTC, arufanov commented on src/main/resources/db/changelog/properties.yml
> +databaseChangeLog:
@yurichervoniy 
this file was crated by you or auto-generated? Looks like auto-generated. Is it correct?

2022-12-01 15:49 UTC, yurichervoniy commented on src/main/java/com/a5lab/tabr/ring/Ring.java
> +@Entity
For maven projects java doc will be generated automatically.
About  java doc - i think we need to discuss it

2022-12-01 15:51 UTC, yurichervoniy commented on src/main/resources/db/changelog/changelog-master.xml
> +    <include file="migrations/2022-11-0000-create-radar-rings-table.xml" relativeToChangelogFile="true"/>
No, i've just decided to use "-" we can use "_" as well. 
I think it's a point to discuss

2022-12-01 15:53 UTC, yurichervoniy commented on src/main/resources/db/changelog/properties.yml
> +databaseChangeLog:
It's hand made =)
I've created the file using old good pattern copy-paste

2022-12-04 10:50 UTC, arufanov approved these changes
Extra issue move to https://github.com/a5lab/tabr/issues/42

2022-12-04 10:50 UTC, arufanov commented on docker/postgresql.yml
> +      - POSTGRES_PASSWORD=tabr
@yurichervoniy 
I use default password: secret. I have changed applicatino.yml. It is good idea to have different name for password and user

2022-12-04 10:50 UTC, arufanov commented on src/main/resources/db/changelog/migrations/2022_11_0000_create_rings_table.xml
> +        <sql>
@yurichervoniy 
* i doubt that sql code is good for myslq, pg & sqlite.

2022-12-04 10:50 UTC, arufanov commented on src/main/resources/db/changelog/migrations/2022_11_0000_create_segments_table.xml
> +        <!-- current Liquibase ignores checkConstraint attribute -->
@yurichervoniy 
* i doubt about sqlite, mysql, pg

2022-12-04 10:50 UTC, arufanov commented on src/main/java/com/a5lab/tabr/ring/Ring.java
> +@Entity
@yurichervoniy 
* ok, thanks! it is related to checkstyle pr.

2022-12-04 10:50 UTC, arufanov commented on src/main/resources/db/changelog/migrations/2022-11-0000-create-radar-rings-table.xml
> +        <createTable tableName="radar_rings" remarks="Holds information about radar rings">
@yurichervoniy 
* move to https://github.com/a5lab/tabr/issues/42

2022-12-04 10:51 UTC, arufanov commented on src/main/resources/db/changelog/data/dictionaries/fill_radar_segments.csv
> +1,Languages,Programming languages,a5lab
https://github.com/a5lab/tabr/issues/42

2022-12-04 10:51 UTC, arufanov commented on src/main/resources/db/changelog/data/dictionaries/fill_radar_segments.csv
> +5,Frameworks,Frameworks we use,a5lab
move to https://github.com/a5lab/tabr/issues/42

2022-12-04 10:52 UTC, arufanov commented on docker/postgresql.yml
> +      - POSTGRES_PASSWORD=tabr
move to https://github.com/a5lab/tabr/issues/42

2022-12-04 10:52 UTC, arufanov commented on src/main/resources/db/changelog/migrations/2022_11_0000_create_segments_table.xml
> +        <!-- current Liquibase ignores checkConstraint attribute -->
move to https://github.com/a5lab/tabr/issues/42

2022-12-04 10:55 UTC, merged